### ISSUE TITLE
Minio BucketExistsAsync 判断桶是否存在与描述不符，如果已经存在应该返回 True

### ISSUE THREAD

**Issue by zgrjhwei** [oncemi/OnceMi.AspNetCore.OSS#1]
如上

![image](https://user-images.githubusercontent.com/55781369/123021630-05acc380-d407-11eb-8d8c-9199f25828db.png)

**Comment by withsalt** [comment]
谢谢你的建议，刚刚修改并测试了以下，发现腾讯云和Minio在创建桶时，如果有相同的桶会抛出异常，阿里云不会。为了尽量让行为与原来的行为保持一致，还是决定再创建桶时有相同的桶抛出异常。
但是有时确实有类似需求，我增加了一个BucketExistException的异常，在创建桶时，可以捕获这个异常，然后做出处理。
