### ISSUE TITLE
腾讯云 COS 列文件返回结果中 isDir 全部为 false

### ISSUE THREAD

**Issue by Robotxm** [oncemi/OnceMi.AspNetCore.OSS#10]
借助本项目获取腾讯云 COS 存储桶文件列表时发现返回结果中所有项目 `isDir` 均为 `true`，不管是文件还是目录。看了下代码这个地方是硬编码了并没有进行判断，不知能否修复呢？

**Comment by oncemi** [comment]
你好，此问题已修复。
原因是腾讯云列出文件列表接口中并无是否表示为目录的参数。但是可以通过文件名称的最后一个字符'/'来判断是否为目录。
