### ISSUE TITLE
Minio PresignedPutObjectAsync方法，1.0.6版功能正常，升级到1.0.7后就不正常了

### ISSUE THREAD

**Issue by yus1977** [oncemi/OnceMi.AspNetCore.OSS#12]
在使用Minio时
启用方法PresignedPutObjectAsync时，同一个对象，在1.0.6版本时正常，升级到1.0.7的所有版本就不正常了
提示信息
MinIO API responded with message=Access Denied

Minio的连接配置为
  "OSSProvider": {
    "Provider": "Minio",
    "Region": "cn-yn",
    "Endpoint": "192.168.0.246:39000",
    "AccessKey": "test",
    "SecretKey": "123456",
    "IsEnableHttps": false,
    "IsEnableCache": true
  }

**Comment by oncemi** [comment]
1.0.6指的是minio版本还是这个SDK版本？

**Comment by yus1977** [comment]
是OnceMi.AspNetCore.OSS的版本
Minio是2022-02-17

**Comment by withsalt** [comment]
抱歉，今天才忙过来。
升级到最新版本试试，从1.0.6到目前版本没有破坏性更新。我测试了目前版本的这个方法没有问题。

**Comment by yus1977** [comment]
多谢！
是我minio授权配置问题
开发环境权限较大，正式环境授权不够
