### ISSUE TITLE
OSS 直传接口

### ISSUE THREAD

**Issue by Axinyp** [oncemi/OnceMi.AspNetCore.OSS#15]
有没有考虑增加OSS 直传接口

**Comment by oncemi** [comment]
OSS 直传接口 指的是？

**Comment by Axinyp** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月8日(周五) 中午11:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [oncemi/OnceMi.AspNetCore.OSS] OSS 直传接口 (Issue #15)




 
OSS 直传接口 指的是？

**Comment by Axinyp** [comment]
就是服务端获取OSS上传凭证设定回调，客户端直接通过链接上传文件，上传完成后OSS 触发回调接口，貌似在OnceMi接口函数
没看到有这个方法
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "oncemi/OnceMi.AspNetCore.OSS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 中午11:44
***@***.***&gt;;
抄送:&nbsp;"泪、只爲你而流 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [oncemi/OnceMi.AspNetCore.OSS] OSS 直传接口 (Issue #15)





 
OSS 直传接口 指的是？

**Comment by withsalt** [comment]
你的意思是异步上传接口接口吧。后台上传完成之后，通过回调方法通知上传完成？

**Comment by Axinyp** [comment]
就服务端签名后将凭证给到调用接口放，并提前设置好回调接口和回调参数




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月9日(星期六) 晚上10:57
收件人: ***@***.***&gt;; 
抄送: "泪、只爲你而流 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [oncemi/OnceMi.AspNetCore.OSS] OSS 直传接口 (Issue #15)





 
你的意思是异步上传接口接口吧。后台上传完成之后，通过回调方法通知上传完成？

**Comment by withsalt** [comment]
没懂你的意思。或许你可以给个demo？
