### ISSUE TITLE
HuaweiOBS兼容.Net 6的问题

### ISSUE THREAD

**Issue by expcat** [oncemi/OnceMi.AspNetCore.OSS#16]
https://github.com/oncemi/OnceMi.AspNetCore.OSS/blob/89289a5091e1d16c56b4990d5a5e4181497f04c2/src/src/OnceMi.AspNetCore.OSS/SDK/HuaweiCloud/Internal/HttpClient.cs#L468-L478

```#if donetcore```
在.net6下无法执行正确的代码，是否修改为？
```#if donetcore || NETSTANDARD2_0_OR_GREATER```

**Comment by oncemi** [comment]
如果测试没问题的话，可以直接提交PR。
但是我更建议给华为云那边提issue，不然下次华为云更新sdk，我们这边还得同步改一下。

**Comment by expcat** [comment]
看了下华为云的SDK，发现应该是缺少了`donetcore`的属性定义
https://github.com/huaweicloud/huaweicloud-sdk-dotnet-obs/blob/f4ed448fd3c97f1951b44646f95502ec84baadc1/esdk_obs_.net_core.csproj#L12-L20
创建了一个pr #17
