### ISSUE TITLE
因为开发机器有时候不具云服务要求，是否考虑同时兼容本地文件夹存储

### ISSUE THREAD

**Issue by zgrjhwei** [oncemi/OnceMi.AspNetCore.OSS#2]

**Comment by withsalt** [comment]
同样感谢你的建议，这个建议暂不考虑。  
首先这个中间件的作用就是为OSS考虑的，其次是本地文件上传的行为和OSS区别太大了，没必要强行适配。我之前在开发的时候也遇到过类似的问题，我的处理方式是再加一层，判断文件到哪里去，然后将文件信息保存到数据库，取文件的时候，先从数据取出文件信息，在判断需要从哪里去取文件。

**Comment by zgrjhwei** [comment]
好的，目前我是这样的思路实现的，谢谢回复
