### ISSUE TITLE
1.20 在发布时会报错：Error NU1605 : 检测到包降级: System.Net.Primitives 从 4.3.0 降级到 4.0.11

### ISSUE THREAD

**Issue by staoran** [oncemi/OnceMi.AspNetCore.OSS#33]
最新的1.20需要更新依赖，否则发布时会警告或报错。

Error NU1605 : Warning As Error: 检测到包降级: System.Net.NameResolution 从 4.3.0 降级到 4.0.0。直接从项目引用包以选择不同版本。 
OnceMi.AspNetCore.OSS 1.2.0 -> BceSdkDotNetCore 1.0.2.911 -> log4net 2.0.8 -> System.Net.Sockets 4.1.0 -> runtime.unix.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0) 
OnceMi.AspNetCore.OSS 1.2.0 -> BceSdkDotNetCore 1.0.2.911 -> log4net 2.0.8 -> System.Net.NameResolution (>= 4.0.0)
Error NU1605 : Warning As Error: 检测到包降级: System.Net.Primitives 从 4.3.0 降级到 4.0.11。直接从项目引用包以选择不同版本。 
OnceMi.AspNetCore.OSS 1.2.0 -> BceSdkDotNetCore 1.0.2.911 -> log4net 2.0.8 -> System.Net.Sockets 4.1.0 -> runtime.unix.System.Net.Sockets 4.3.0 -> System.Net.Primitives (>= 4.3.0) 
OnceMi.AspNetCore.OSS 1.2.0 -> BceSdkDotNetCore 1.0.2.911 -> log4net 2.0.8 -> System.Net.Sockets 4.1.0 -> System.Net.Primitives (>= 4.0.11)
Error NU1605 : Warning As Error: 检测到包降级: System.Net.NameResolution 从 4.3.0 降级到 4.0.0。直接从项目引用包以选择不同版本。 
OnceMi.AspNetCore.OSS 1.2.0 -> BceSdkDotNetCore 1.0.2.911 -> log4net 2.0.8 -> System.Net.Sockets 4.1.0 -> runtime.unix.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0) 
OnceMi.AspNetCore.OSS 1.2.0 -> BceSdkDotNetCore 1.0.2.911 -> log4net 2.0.8 -> System.Net.NameResolution (>= 4.0.0)

**Comment by withsalt** [comment]
OnceMi.AspNetCore.OSS项目引用的BceSdkDotNetCore中使用了 System.Net.NameResolution 4.0版本。
可以在引用OnceMi.AspNetCore.OSS强制引用System.Net.NameResolution 4.3.0来解决这个问题

**Comment by staoran** [comment]
是的，很蛋疼😄
