### ISSUE TITLE
minio的https访问BucketExistsAsync报错

### ISSUE THREAD

**Issue by YBenX** [oncemi/OnceMi.AspNetCore.OSS#4]
通过nginx转发出来并配置好了https，直接网站访问没有问题
有个Bucket：pppp，使用ListBucketsAsync可以查询到pppp。
调用BucketExistsAsync就报异常
MinIO API responded with message=Access denied on the resource: pppp/

通过IP+Port没有报异常

**Comment by withsalt** [comment]
nginx反向代理之后通过域名的吗？域名是否有端口？

**Comment by withsalt** [comment]
已复现，我会尽快找到原因。

**Comment by withsalt** [comment]
已修复。

**Comment by YBenX** [comment]
正常了，谢谢，还一直为是我的nginx配置的有问题

**Comment by YBenX** [comment]
![XZ3_@QJXNG`UL6Q)QKQLH4](https://user-images.githubusercontent.com/3353434/127956265-e74f85be-90ca-4f31-b055-8aa502cd3103.png)
Nginx配置一下这个可以解决这个问题，不用把HEAD方法改成GET，官方给的Java的SDK也是用HEAD方法去请求

**Comment by withsalt** [comment]
晚点我测试一下。java直接使用head方式直接请求nginx反代后的域名正常吗？我没有测试过java的SDK。

**Comment by YBenX** [comment]
> 晚点我测试一下。java直接使用head方式直接请求nginx反代后的域名正常吗？我没有测试过java的SDK。

Java的sdk我试也是和你的一样的错误，原因是我的Nginx没有配置Head，配置了这段代码后，就支持Head请求了，所以你可以不用改那个HEAD为GET，好像官方的就是用HEAD吧？Nginx配置好就行了
```
if ($request_method ~ ^(HEAD)$ ) {
        return 200 "All OK";
    }
```

**Comment by withsalt** [comment]
`
if ($request_method ~ ^(HEAD)$ ) {
        return 200 "All OK";
    }
`
这样配置的话，不关bucket存不存在，返回都是存在。
